# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

class Loja:
    def __init__(self, nome):
        self.nome = nome
        self.preco = 0
        self.quantidade_produzida = 0
        self.propaganda = 0
        self.vendedores = 0
        self.faturamento = 0
        self.quantidade_vendida = 0
        self.diferenca_prev_vend = 0

    def calcular_resultados(self, sazonalidade_total, num_lojas, media_preco, media_propaganda, media_vendedores):
        # Fórmulas para calcular quantidade vendida e faturamento
        self.quantidade_vendida = int(
            sazonalidade_total / num_lojas * ((media_preco / self.preco) * 0.5 +
                                              (self.propaganda / media_propaganda) * 0.3 +
                                              (self.vendedores / media_vendedores) * 0.2)
        )
        self.diferenca_prev_vend = self.quantidade_produzida - self.quantidade_vendida
        self.faturamento = self.quantidade_vendida * self.preco


def obter_media(lista_valores):
    return sum(lista_valores) / len(lista_valores)


def main():
    print("Bem-vindo ao jogo das lojas de camisas do Daniel Saboya!")
    print("Você gerenciará lojas de camisas durante a turnê de shows do Daniel Saboya.")
    print("Faça as decisões estratégicas para maximizar o faturamento da sua loja.")

    # Selecionar número de lojas (mínimo 2, máximo 5)
    while True:
        try:
            num_lojas = int(input("Quantas lojas irão competir? (Escolha entre 2 e 5): "))
            if 2 <= num_lojas <= 5:
                break
            else:
                print("Por favor, escolha um número entre 2 e 5.")
        except ValueError:
            print("Entrada inválida. Digite um número entre 2 e 5.")

    lojas = [Loja(f"Loja {i+1}") for i in range(num_lojas)]

    sazonalidade_total = 300_000  # Valor ajustado de sazonalidade total para a turnê

    for loja in lojas:
        print(f"\nDecisões para {loja.nome}:")
        loja.preco = float(input("Preço por camisa (em R$): "))
        loja.quantidade_produzida = int(input("Quantidade de camisas a serem produzidas: "))
        loja.propaganda = float(input("Investimento em propaganda (em R$): "))
        loja.vendedores = int(input("Número de vendedores na loja: "))

    # Calcular médias das decisões
    media_preco = obter_media([loja.preco for loja in lojas])
    media_propaganda = obter_media([loja.propaganda for loja in lojas])
    media_vendedores = obter_media([loja.vendedores for loja in lojas])

    # Calcular resultados de cada loja
    for loja in lojas:
        loja.calcular_resultados(sazonalidade_total, num_lojas, media_preco, media_propaganda, media_vendedores)

    # Mostrar resultados
    print("\nResultados finais:")
    for loja in lojas:
        print(f"{loja.nome}:")
        print(f"  Faturamento: R$ {loja.faturamento:.2f}")
        print(f"  Quantidade vendida: {loja.quantidade_vendida}")
        print(f"  Diferença produção/venda: {loja.diferenca_prev_vend}")

    # Determinar o vencedor
    vencedor = max(lojas, key=lambda l: l.faturamento)
    print(f"\nA loja vencedora é {vencedor.nome} com um faturamento de R$ {vencedor.faturamento:.2f}!")
    print("Parabéns! Daniel Saboya agradece o apoio às vendas durante a turnê!")


if __name__ == "__main__":
    main()